sudo: required

language: generic

services:
- docker

before_install:
- docker pull scottfleischman/agda:2.5.4

env:
- AGDA_FILE="src/Example.agda"

script:
- docker run -v $TRAVIS_BUILD_DIR:/opt/agda-build scottfleischman/agda:2.5.4 /bin/sh -c 'cd /opt/agda-build; agda '$AGDA_FILE
