sudo: required

language: generic

services:
- docker

before_install:
- docker pull scottfleischman/agda:2.5.4.1

script:
- docker run -v $TRAVIS_BUILD_DIR:/opt/agda-build scottfleischman/agda:2.5.4.1 /bin/sh -c 'cd /opt/agda-build && agda src/Example.agda'
- >
  docker run -v $TRAVIS_BUILD_DIR:/opt/agda-build scottfleischman/agda:2.5.4.1 /bin/sh -c
  'cd /opt/agda-build && \
   agda --compile --ghc-dont-call-ghc src/HelloWorld.agda && \
   stack ghc --system-ghc --resolver lts-12.6 --package ieee754 -- -O -o HelloWorld -isrc -main-is MAlonzo.Code.HelloWorld src/MAlonzo/Code/HelloWorld.hs && \
   ./HelloWorld'
